### ISSUE TITLE
Peer to peer review 

### ISSUE THREAD

**Issue by SirriRyisa** [BertrandConxy/The-Portfolio#12]
Nice work Bertrand. we have gone through the entire together and all we can say is good work done. 

Organized code structure, clear logic, and brilliant HTML structure. 

Popup functions in desktop and mobile are responsive. 

No linter errors

**Comment by steveWDamesJr** [comment]
Great Work. No deficiencies detected. Project functioning and working as should. 
Great Semantics and Accessibility optimized through standard measures such as including all ALT text on images.

**Comment by BertrandConxy** [comment]
Thank you very much everyone for the comments. I really appreciate it. 😄 💯
