### ISSUE TITLE
Bug found in Bertrand's project

### ISSUE THREAD

**Issue by Yerimah** [BertrandConxy/The-Portfolio#15]
@BertrandConxy You have done an amazing job on this project. However, there was a bug found on your email validation code in Javascript on ***line 202***

The function `id(textContainer)` produced a referenceError which prevented the error message from displaying. I debugged this error using the chrome developer tool and fixed it by replacing it with `form.appendchild(textContainer)`

Secondly, there was no `html` element for the error message content. This was fixed by adding a `textContainer.innerHTML = ` That contains the error message.

**Comment by BertrandConxy** [comment]
Thank you very much @Yerimah the bug was fixed.
